BOT_TOKEN = '7902381079:AAFmcDNUo0D2qDJ-_rGaltb-Phil-hYe71Y'
PAYMENT_API_URL = '---'
ADMIN_ID = 'https://t.me/vversion'
FREE_ROOM_LIMIT = 5
PAID_ROOM_LIMIT = 10
PRICE_SINGLE_ACCESS = 99
PRICE_FULL_ACCESS = 799
DB_PATH = 'Santa_bot.db'
